### ISSUE TITLE
error while running oracle

### ISSUE THREAD

**Issue by gyulaweber** [stef/pwdsphinx#1]
I've tried to build pwdsphinx, but when I run oracle, I got this error message (see below).
I've created a Dockerfile: https://github.com/gyulaweber/build_sphinx to see what I did (the sequence of the commands reflects the sequence of dependencies).

Any suggestion is most appreciated :)

```
root@dd719ac08b16:/opt# oracle
Traceback (most recent call last):
  File "/usr/local/bin/oracle", line 11, in <module>
    load_entry_point('pwdsphinx==0.3.1', 'console_scripts', 'oracle')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/pwdsphinx/oracle.py", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

**Comment by stef** [comment]
sorry, i hate to admit it, but pwdsphinx is py3 only.

**Comment by stef** [comment]
at least the frontends. sphinxlib.py should be both py2 and py3.
